#!/usr/bin/python3
import sys

def factorize(number):
    factors = []
    for i in range(2, number + 1):
        if number % i == 0:
            factors.append(i)
            factors.append(number // i)
            break
    return (factors)

def main(input_file):
    with open(input_file, 'r') as file:
        lines = file.read().splitlines()
        for line in lines:
            number = int(line)
            factors = factorize(number)
            if len(factors) >= 2:
                p = factors[1]
                q = factors[0]
                print(f"{number}={p}*{q}")
if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(1)
    input_file = sys.argv[1]
    main(input_file)

